package exercise.exception;

public class ArithmeticExThrows {
    public static void main(String[] args) {
        try{
//            int result = divide(10, 0);
        } catch (ArithmeticException e) {
            System.out.println("내가 대신 처리함");
        }


    }

//    public static int divide(int x, int y) {
//        throw ArithmeticException {
//            int result = 0;
//            result = x / y;
//            return result;
//        }
//
//    }
}

